name: "CI 🤖"

on:
  pull_request:
    branches: [ main ]


jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 
        with:
          node-version: 16


      - name: Install NPM Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      
      - name: Clean
        run: npm run clean:dist
      
      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build 
      
      - name: Test
        run: npm run test:ci:cov

      - name: "Publish results"
        - uses: npm run discord
          with:
            GITHUB_TOKEN: ${{ secrets.GH_CI_BOT_TOKEN }}
            DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
       

